/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as NoteAuthenticatedImport } from './routes/note/_authenticated'
import { Route as NoteNoteIdImport } from './routes/note/$noteId'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardImport } from './routes/_authenticated/dashboard'
import { Route as NoteAuthenticatedCreateImport } from './routes/note/_authenticated/create'
import { Route as NoteAuthenticatedNoteIdEditImport } from './routes/note/_authenticated/$noteId/edit'

// Create Virtual Routes

const NoteImport = createFileRoute('/note')()

// Create/Update Routes

const NoteRoute = NoteImport.update({
  path: '/note',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NoteAuthenticatedRoute = NoteAuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => NoteRoute,
} as any)

const NoteNoteIdRoute = NoteNoteIdImport.update({
  path: '/note/$noteId',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const NoteAuthenticatedCreateRoute = NoteAuthenticatedCreateImport.update({
  path: '/create',
  getParentRoute: () => NoteAuthenticatedRoute,
} as any)

const NoteAuthenticatedNoteIdEditRoute =
  NoteAuthenticatedNoteIdEditImport.update({
    path: '/$noteId/edit',
    getParentRoute: () => NoteAuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/dashboard': {
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile': {
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/note/$noteId': {
      preLoaderRoute: typeof NoteNoteIdImport
      parentRoute: typeof rootRoute
    }
    '/note': {
      preLoaderRoute: typeof NoteImport
      parentRoute: typeof rootRoute
    }
    '/note/_authenticated': {
      preLoaderRoute: typeof NoteAuthenticatedImport
      parentRoute: typeof NoteRoute
    }
    '/note/_authenticated/create': {
      preLoaderRoute: typeof NoteAuthenticatedCreateImport
      parentRoute: typeof NoteAuthenticatedImport
    }
    '/note/_authenticated/$noteId/edit': {
      preLoaderRoute: typeof NoteAuthenticatedNoteIdEditImport
      parentRoute: typeof NoteAuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthenticatedRoute.addChildren([
    AuthenticatedDashboardRoute,
    AuthenticatedProfileRoute,
  ]),
  LoginRoute,
  NoteNoteIdRoute,
  NoteRoute.addChildren([
    NoteAuthenticatedRoute.addChildren([
      NoteAuthenticatedCreateRoute,
      NoteAuthenticatedNoteIdEditRoute,
    ]),
  ]),
])

/* prettier-ignore-end */
